<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net452;netstandard2.0;net8.0;net10.0</TargetFrameworks>
    <RootNamespace>OneSpanSign.Sdk</RootNamespace>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>sdk.snk</AssemblyOriginatorKeyFile>
    <DelaySign>false</DelaySign>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>OneSpan Dev</Authors>
    <Company>OneSpan</Company>
    <Product>OneSpan Sign SDK</Product>
    <Version>11.69.0</Version>
    <Copyright>OneSpan</Copyright>
    <Description>.NET SDK for OneSpan Sign</Description>
    <PackageProjectUrl>https://github.com/OneSpan/oss.sdk.net</PackageProjectUrl>
    <RepositoryUrl>https://github.com/OneSpan/oss.sdk.net</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net452'">
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
